const english = {
    home:"home",
    about:"about",
    skills:"skills",
    experiances:"experiances",
    contact:"contact",
    welcome:"Hi, my name is",
    name:"samir Nabil",
    title:"I build things for the web",
    describe:"I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products at SimpleWeb",
    viewArticles:" check out my articls. !",
    aboutTitle:"about me",
    aboutInfo:"Hello! My name is Samir and I enjoy creating things that live on the internet. My interest in web development started back in 2018 when I decided to try lrean Html, css and Js on YouTube for fun at the beginingFast-forward , i move to advanced and profisional courses in frontend like nodeJs react and redux on international platform like coursera ,udemy udacity ,maharatich and i do make some simple website to move from study to apply real project now i still apply what i learned in real website and i am translating articls for my website which consider as a cv for me seeking agood opprtunuty in good team or in company",
    reactDesc:"React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.Declarative views make your code more predictable and easier to debug.",
    axiosDesc:"Axios launched in January 2017 based on this shared belief: The world needed smarter, more efficient coverage of the topics shaping the fast-changing world. . Now, they are focusing our minds and manpower on a much bigger problem faced by all consumers: the erosion of truth, trust, safety and sanity in news. This is an existential threat to our democracy. It will require extraordinary effort by them and others to correct. ",
    reduxDesc:"It helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test. On top of that, it provides a great developer experience, such as live code editing combined with a time traveling debugger.",
    sassDesc:"Sass is a stylesheet language that’s compiled to CSS. It allows you to use variables, nested rules, mixins, functions, and more, all with a fully CSS-compatible syntax. Sass helps keep large stylesheets well-organized and makes it easy to share design within and across projects.",
    react:" ( react )",
    sass:" (scss) ",
    axios:" (axios)",
    redux:" (redux) ",
    feacheredProject:"feachered Project",
    Edgeledger:"accounting project Edgeledger",
    EdgeledgerDesc:" It is an accounting application that was uploaded to GitHub with fake data. It is a single page that is navigated through scroll ",
    Hotel:"Hotel ahotel project ",
    hotelDesc: "A fake application with dummy css data A multi-page application hosted on GitHub The float technology was used and more than one page was made, and the transfer through the link The project is primitive The aim of the project is to master float and some features in",
    whatIsNext:"wht is next",
    contactWithUs:"get in touch ",
    contactUsDesc:" I am now working as a freelancer, and I am happy to communicate with you and leave a message or an impression of the site or opinion or suggestion or business partnership or help you to create your own site.",
    contactNow:"contact now",
    articls:"articls",
    visit:"visit",
    exporiances:"exporiances",
}
export default english


